Also added linting to commit

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,5 +1,12 @@
 #!/bin/bash
 
+npm run lint
+
+if [ $? -ne 0 ]; then
+  echo "Linting failed. Aborting commit."
+  exit 1
+fi
+
 npm run format
 
 # Store the edited files in an array
